config/routes.rb
Rails.application.routes.draw do

root 'welcome#index'

  get "inicio/maestro"

post "welcome" => "welcome#validar"

  namespace :admin do
    get '/', to: 'dashboard#index'
    get '/usuarios', to: 'admins#new'
     get 'pregunta/nueva', to: 'preguntas#new'
     get 'pregunta/', to: "preguntas#index"
     get "pregunta/:id" => "preguntas#show"
get'quizz/', to: 'quizzs#index'

     get'quizz/nuevo', to: 'quizzs#new'
     get'tema/nuevo', to: 'temas#new'

    get'tema/editar', to: 'temas#edit'
    get'tema/mostrar', to: 'temas#show'
        get'tema/', to: 'temas#index'

  post 'tema/actualizar', to: 'temas#update'
        get'temario/nuevo', to: 'temario#new'

       get'temario/editar', to: 'temarios#edit'
       get'temario/mostrar', to: 'temarios#show'
           get'temario/', to: 'temarios#index'

    resources :preguntas
    resource :admin
    resources :quizzs
    resources :temas
    resources :temarios
  end
  namespace :maestro do
    get '/', to: 'dashboard#index'
    get '/grupo', to: 'dashboard#grupo'
      get '/grafica', to: 'dashboard#grafica'
      get '/gestion', to: "dashboard#gestion"
  end
  namespace :alumno do
    get '/', to: 'dashboard#index'
    post 'codigo', to: 'dashboard#validarCodigo'
    get 'esperar', to: 'dashboard#esperar'
    get 'respuestas', to: 'dashboard#respuestas'
    get 'enviada', to: 'dashboard#enviada'
    get 'puntaje', to: 'dashboard#puntaje'
  end

end

app/models/pregunta.rb
class Pregunta < ActiveRecord::Base
  validates(:texto, presence: true)
  validates(:respuesta1, presence: true)
    validates(:respuesta2, presence: true)
      validates(:respuesta3, presence: true)
        validates(:respuesta4, presence: true)
 has_and_belongs_to_many :quizzs
mount_uploader :image, ImageUploader
end

app/controllers/admin/preguntas_controller.rb
class Admin::PreguntasController < ApplicationController

  def index
    @preguntas = Pregunta.all.paginate(page: params[:page], per_page: 10)
  end

  def new
    @path_prefix = :admin
    @pregunta = Pregunta.new
  end

  def show
    @pregunta = Pregunta.find(params[:id])
  end

  def create
    @pregunta = Pregunta.new(pregunta_params)
    if @pregunta.save
      redirect_to :action => :show, :id => @pregunta.id
    else
      render :new
    end
  #@pregunta = Pregunta.new(pregunta_params)
  end

  def edit
    # @path_prefix = :admin
    @pregunta = Pregunta.find(params[:id])


  end

   private
     def pregunta_params
       params.require(:pregunta).permit(:image, :texto,  :respuesta1,:respuesta2, :respuesta3, :respuesta4, :tiempo)
     end


end

app/helpers/pregunta_helper.rb
module PreguntaHelper
end

app/views/admin/preguntas/_form.html.erb
<%= form_for :pregunta, :url => { :action => :create} do |f| %>
  <% if @pregunta.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pregunta.errors.count, "error") %> prohibited this question from being saved:</h2>
      <ul>
      <% @pregunta.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Suba la imagen" %><br>
    <%= f.file_field :image %>
  </div>

  <div class="field">
    <%= f.label :texto %><br>
    <%= f.text_field :texto %>
  </div>
  <div class="field">
    <%= f.label :respuesta1 %><br>
    <%= f.text_field :respuesta1 %>
  </div>
  <div class="field">
    <%= f.label :respuesta2 %><br>
    <%= f.text_field :respuesta2 %>
  </div>
  <div class="field">
    <%= f.label :respuesta3 %><br>
    <%= f.text_field :respuesta3 %>
  </div>
  <div class="field">
    <%= f.label :respuesta4 %><br>
    <%= f.text_field :respuesta4 %>
  </div>
  <div class="field">
    <%= f.label :tiempo %><br>
    <%= f.number_field :tiempo %>
  </div>
  <div class="actions">
    <%= f.submit "Guardar Pregunta" %>
  </div>
<% end %>

app/views/admin/preguntas/edit.html.erb
<h1>editar pregunta</h1>

<%= render 'form' %>

<%= link_to 'atras', admin_preguntas_path %>

app/views/admin/preguntas/index.html.erb
<p id="notice"><%= notice %></p>


<h1>preguntas</h1>

<table>
  <thead>
    <tr>
      <th>Texto</th>
        <th>Respuesta 1</th>
          <th>Respuesta 2 </th>
            <th>Respuesta 3 </th>
              <th>Respuesta 4 </th>

      <th>Tiempo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @preguntas.each do |pregunta| %>
      <tr>
        <td><%= pregunta.texto %></td>
          <td><%= pregunta.respuesta1 %></td>
            <td><%= pregunta.respuesta2 %></td>
              <td><%= pregunta.respuesta3 %></td>
                <td><%= pregunta.respuesta4 %></td>

        <td><%= pregunta.tiempo %></td>
        <td><%= link_to 'Show', admin_pregunta_path(pregunta) %></td>
        <td><%= link_to 'Edit', edit_admin_pregunta_path(pregunta) %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @preguntas,  :previous_label => 'Atrás', :next_label => 'Adelante'%>
<br>

<%= link_to 'Nueva pregunta', new_admin_pregunta_path %>

app/views/admin/preguntas/new.html.erb
<h1>Nueva pregunta</h1>

<%= render 'form' %>

<%= link_to 'atras', admin_preguntas_path %>

app/views/admin/preguntas/show.html.erb
<p>
  <strong>Texto:</strong>
  <%= @pregunta.texto %>
</p>

<p>
  <strong>Image:</strong>
  <%= image_tag @pregunta.image %>
</p>

<p>
  <strong>Respuesta 1 (correcta):</strong>
  <%= @pregunta.respuesta1 %>
</p>

<p>
  <strong>Respuesta 2 (incorrecta):</strong>
  <%= @pregunta.respuesta2 %>
</p>

<p>
  <strong>Respuesta 3 (incorrecta):</strong>
  <%= @pregunta.respuesta3 %>
</p>


<p>
  <strong>Respuesta 4 (incorrecta):</strong>
  <%= @pregunta.respuesta4 %>
</p>

<p>
  <strong>Tiempo de pregunta:</strong>
  <%= @pregunta.tiempo %>
</p>