config/routes.rb
Rails.application.routes.draw do

root 'welcome#index'

  get "inicio/maestro"

post "welcome" => "welcome#validar"

  namespace :admin do
    get '/', to: 'dashboard#index'
    get '/usuarios', to: 'admins#new'
     get 'pregunta/nueva', to: 'preguntas#new'
     get 'pregunta/', to: "preguntas#index"
     get "pregunta/:id" => "preguntas#show"
get'quizz/', to: 'quizzs#index'

     get'quizz/nuevo', to: 'quizzs#new'
     get'tema/nuevo', to: 'temas#new'

    get'tema/editar', to: 'temas#edit'
    get'tema/mostrar', to: 'temas#show'
        get'tema/', to: 'temas#index'

  post 'tema/actualizar', to: 'temas#update'
        get'temario/nuevo', to: 'temario#new'

       get'temario/editar', to: 'temarios#edit'
       get'temario/mostrar', to: 'temarios#show'
           get'temario/', to: 'temarios#index'

    resources :preguntas
    resource :admin
    resources :quizzs
    resources :temas
    resources :temarios
  end
  namespace :maestro do
    get '/', to: 'dashboard#index'
    get '/grupo', to: 'dashboard#grupo'
      get '/grafica', to: 'dashboard#grafica'
      get '/gestion', to: "dashboard#gestion"
  end
  namespace :alumno do
    get '/', to: 'dashboard#index'
    post 'codigo', to: 'dashboard#validarCodigo'
    get 'esperar', to: 'dashboard#esperar'
    get 'respuestas', to: 'dashboard#respuestas'
    get 'enviada', to: 'dashboard#enviada'
    get 'puntaje', to: 'dashboard#puntaje'
  end

end

app/models/quizz.rb
class Quizz < ActiveRecord::Base
validates_uniqueness_of :nombre
 validates(:nombre, presence: true)
  belongs_to :tema
   has_and_belongs_to_many :preguntas
end

app/controllers/admin/quizzs_controller.rb
class Admin::QuizzsController < ApplicationController

  def index
    @quizzes = Quizz.all
    @temas=Tema.all

  end

def new
 @tema_options = Tema.all.map{ |t| [ t.nombretema, t.id ] }
    @preguntas = Pregunta.all
  @path_prefix = :admin
  @quizz = Quizz.new
end

def show

    @quizz = Quizz.find(params[:id])
      @temas=Tema.all
end

def create
  @quizz = Quizz.new(quizz_params)
  if @quizz.save
    redirect_to :action => :show, :id => @quizz.id
  else
    render :new
  end


end

def edit

@quizz = Quizz.find(params[:id])
@tema_options = Tema.all.map{ |t| [ t.nombretema, t.id ] }
   @preguntas = Pregunta.all
end

private
  def quizz_params
   params.require(:quizz).permit(:nombre, :disponible, :temaid)
  end



end

app/helpers/quizzs_helper.rb
module QuizzsHelper
end

app/views/admin/quizzs/_form.html.erb
<h1>Formulario de Quizzes</h1>
<%= form_for :quizz, :url => { :action => :create} do |f| %>
<div class="field">
  <%= f.label "Introduzca el nombre del Quizz" %><br>
  <%= f.text_field :nombre %>
</div>

<div class="field">

  <%= label_tag(:disp, "¿El quizz esta disponible para usarse?") %>
  <%= f.check_box :disponible %>
</div>
<div class="field">

  <%= f.label "Elija un tema" %>
    <%= f.select(:temaid,@tema_options) %>
</div>
<div class="field">
  <br>
  <br>
  <% @preguntas.each do |pre| %>
      <div>
  <%= check_box_tag :preguntas_id -%>
  <%= label_tag :preguntas, pre.texto-%>
      </div>
    <% end %>
  
  </div>
  <div class="actions">
    <%= f.submit "Guardar Quizz" %>
  </div>
<% end %>

app/views/admin/quizzs/edit.html.erb
<h1>Editar Quizz</h1>
<%= render 'form' %>

app/views/admin/quizzs/index.html.erb
<h1>Index Quizzes</h1>

<p id="notice"><%= notice %></p>

<h1>Quizzes</h1>


<table border="1">
  <col width="150">
  <col width="160">
  <col width="150">
  <col width="50">
  <thead>
    <tr>
      <th>Nombre del quizz</th>
        <th>Disponibilidad</th>
          <th>Tema</th>


      <th colspan="5"></th>
    </tr>
  </thead>

  <tbody>
    <% @quizzes.each do |q| %>
      <tr>
        <td><%= q.nombre %></td>
          <% if q.disponible? %>
<td> Disponible</td>
            <% else %>
<td> No Disponible</td>
              <% end %>

              <% @temas.each do |t| %>


                    <% if (t.id==q.temaid) %>
            <td><%= t.nombretema %></td>

  <% end %>
                        <% end %>
                          <td><%= link_to 'Show', controller: "quizzs", action: "show", id: q.id  %></td>
  <td><%= link_to 'Edit', edit_admin_quizz_path(q) %></td>


    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo quizz', new_admin_quizz_path %>

app/views/admin/quizzs/new.html.erb
<h1>Crear nuevo quizz</h1>
<%= render 'form' %>

app/views/admin/quizzs/show.html.erb
<h1>Mostrar Quizz</h1>
<h1>Quizz</h1>

<p>
  <strong>Nombre:</strong>
  <%= @quizz.nombre %>
</p>


<p>
  <strong>Disponibilidad:</strong>


<% if  @quizz.disponible? %>
 Disponible
  <% else %>
 No Disponible
    <% end %>

</p>
    <p>
      <strong>Tema:</strong>


    <% @temas.each do |t| %>


          <% if (t.id==@quizz.temaid) %>
    <%= t.nombretema %>

    <% end %>
    <% end %>
</p>
<%= link_to 'Index', admin_quizzs_path %>
<%= link_to 'Atras',:back %>