config/routes.rb
Rails.application.routes.draw do

root 'welcome#index'

  get "inicio/maestro"

post "welcome" => "welcome#validar"

  namespace :admin do
    get '/', to: 'dashboard#index'
    get '/usuarios', to: 'admins#new'
     get 'pregunta/nueva', to: 'preguntas#new'
     get 'pregunta/', to: "preguntas#index"
     get "pregunta/:id" => "preguntas#show"
get'quizz/', to: 'quizzs#index'

     get'quizz/nuevo', to: 'quizzs#new'
     get'tema/nuevo', to: 'temas#new'

    get'tema/editar', to: 'temas#edit'
    get'tema/mostrar', to: 'temas#show'
        get'tema/', to: 'temas#index'

  post 'tema/actualizar', to: 'temas#update'
        get'temario/nuevo', to: 'temario#new'

       get'temario/editar', to: 'temarios#edit'
       get'temario/mostrar', to: 'temarios#show'
           get'temario/', to: 'temarios#index'

    resources :preguntas
    resource :admin
    resources :quizzs
    resources :temas
    resources :temarios
  end
  namespace :maestro do
    get '/', to: 'dashboard#index'
    get '/grupo', to: 'dashboard#grupo'
      get '/grafica', to: 'dashboard#grafica'
      get '/gestion', to: "dashboard#gestion"
  end
  namespace :alumno do
    get '/', to: 'dashboard#index'
    post 'codigo', to: 'dashboard#validarCodigo'
    get 'esperar', to: 'dashboard#esperar'
    get 'respuestas', to: 'dashboard#respuestas'
    get 'enviada', to: 'dashboard#enviada'
    get 'puntaje', to: 'dashboard#puntaje'
  end

end

app/models/temario.rb
class Temario < ActiveRecord::Base
  validates_uniqueness_of :nombretemario
   validates(:nombretemario, presence: true)
   validates(:descripcion, presence: true)
  has_many :temas
end

app/controllers/admin/temarios_controller.rb
class Admin::TemariosController < ApplicationController




  def index
    @temario = Temario.all.paginate(page: params[:page], per_page: 10)
  end

  def new
    @path_prefix = :admin
    @temario = Temario.new
  end

  def show
    @path_prefix = :admin
    @temario = Temario.find(params[:id])
@temas=Tema.where(temarioid: @temario.id ).paginate(page: params[:page], per_page: 10)
  end

  def create
    @temario = Temario.new(temario_params)
    if @temario.save
      redirect_to :action => :show, :id => @temario.id
    else
      render :new
    end

  end

  def edit
    # @path_prefix = :admin
    @temario = Temario.find(params[:id])
  end

   private
     def temario_params
       params.require(:temario).permit(:nombretemario, :descripcion)
     end


end

app/helpers/temarios_helper.rb
module TemariosHelper
end

app/views/admin/temarios/_form.html.erb
<%= form_for :temario, :url => { :action => :create} do |f| %>
  <% if @temario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@temario.errors.count, "error") %> prohibited this question from being saved:</h2>
      <ul>
      <% @temario.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Escriba el nombre del temario" %><br>
    <%= f.text_field :nombretemario %>
  </div>

  <div class="field">
    <%= f.label "Escriba la descripción del temario" %><br>
    <%= f.text_field :descripcion %>
  </div>

  <div class="actions">
    <%= f.submit "Guardar Temario" %>
  </div>
<% end %>

app/views/admin/temarios/edit.html.erb
<h1>Editar temario</h1>
<%= render 'form' %>
<%= link_to 'Atras', admin_temarios_path %>

app/views/admin/temarios/index.html.erb

<p id="notice"><%= notice %></p>

<h1>Temarios</h1>

<table border="1">
  <col width="150">
  <col width="160">
  <col width="150">

  <thead>
    <tr>
      <th>Nombre del temario</th>
        <th>Descripción</th>


      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @temario.each do |t| %>
      <tr>
        <td><%= t.nombretemario %></td>
          <td><%= t.descripcion %></td>


        <td><%= link_to 'Show', controller: "temarios", action: "show", id: t.id  %></td>
        <td><%= link_to 'Editar', edit_admin_temario_path(t) %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @temario,  :previous_label => 'Atrás', :next_label => 'Adelante'%>
<br>

<%= link_to 'Nuevo temario', new_admin_temario_path %>

app/views/admin/temarios/new.html.erb
<h1>Nuevo tema</h1>
<%= render 'form' %>
<%= link_to 'Atras', admin_temarios_path %>

app/views/admin/temarios/show.html.erb
<h1>Tema</h1>

<p>
  <strong>Nombre:</strong>
  <%= @temario.nombretemario %>
</p>

<p>
  <strong>Descripción:</strong>
  <%= @temario.descripcion %>
</p>



<table border="1">
  <col width="150">
  <col width="160">
  <col width="150">

  <thead>
    <tr>
      <th>Nombre del tema</th>
        <th>Descripción</th>


      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @temas.each do |tema| %>
      <tr>
        <td><%= tema.nombretema %></td>
          <td><%= tema.descripcion %></td>


        <td><%= link_to 'Show', controller: "temas", action: "show", id: tema.id  %></td>
        <td><%= link_to 'Editar', edit_admin_tema_path(tema) %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @temas,  :previous_label => 'Atrás', :next_label => 'Adelante'%>
<br>


<%= link_to 'Index', admin_temarios_path %>
<%= link_to 'Atras',:back %>