config/routes.rb
Rails.application.routes.draw do

root 'welcome#index'

  get "inicio/maestro"

post "welcome" => "welcome#validar"

  namespace :admin do
    get '/', to: 'dashboard#index'
    get '/usuarios', to: 'admins#new'
     get 'pregunta/nueva', to: 'preguntas#new'
     get 'pregunta/', to: "preguntas#index"
     get "pregunta/:id" => "preguntas#show"
get'quizz/', to: 'quizzs#index'

     get'quizz/nuevo', to: 'quizzs#new'
     get'tema/nuevo', to: 'temas#new'

    get'tema/editar', to: 'temas#edit'
    get'tema/mostrar', to: 'temas#show'
        get'tema/', to: 'temas#index'

  post 'tema/actualizar', to: 'temas#update'
        get'temario/nuevo', to: 'temario#new'

       get'temario/editar', to: 'temarios#edit'
       get'temario/mostrar', to: 'temarios#show'
           get'temario/', to: 'temarios#index'

    resources :preguntas
    resource :admin
    resources :quizzs
    resources :temas
    resources :temarios
  end
  namespace :maestro do
    get '/', to: 'dashboard#index'
    get '/grupo', to: 'dashboard#grupo'
      get '/grafica', to: 'dashboard#grafica'
      get '/gestion', to: "dashboard#gestion"
  end
  namespace :alumno do
    get '/', to: 'dashboard#index'
    post 'codigo', to: 'dashboard#validarCodigo'
    get 'esperar', to: 'dashboard#esperar'
    get 'respuestas', to: 'dashboard#respuestas'
    get 'enviada', to: 'dashboard#enviada'
    get 'puntaje', to: 'dashboard#puntaje'
  end

end

app/models/tema.rb
class Tema < ActiveRecord::Base
    validates_uniqueness_of :nombretema
    validates(:nombretema, presence: true)
    validates(:descripcion, presence: true)
  has_many :quizzs
  belongs_to :temario
end

app/controllers/admin/temas_controller.rb
class Admin::TemasController < ApplicationController

  def index
    @tema = Tema.all.paginate(page: params[:page], per_page: 10)
  end

  def new
     @temarios_options = Temario.all.map{ |te| [ te.nombretemario, te.id ] }
    @path_prefix = :admin
    @tema = Tema.new
  end

  def show
    @path_prefix = :admin
    @tema = Tema.find(params[:id])
      @quizzes=Quizz.where(temaid: @tema.id ).paginate(page: params[:page], per_page: 10)
  end

  def create
    @tema = Tema.new(tema_params)

    if @tema.save
      redirect_to :action => :show, :id => @tema.id
    else
      render :new
    end

  end

  def edit
    # @path_prefix = :admin

    @tema = Tema.find(params[:id])

  #redirect_to :action => :show, :id => @tema.id
  end
def update
  @tema = Tema.find(params[:id])
if @tema.update_attributes(tema_params)
  redirect_to :action => :show, :id => @tema.id
else
render 'edit'
end
end


   private
     def tema_params
       params.require(:tema).permit(:nombretema, :descripcion, :temarioid)
     end

end

app/helpers/temas_helper.rb
module TemasHelper
end

app/views/admin/temas/_form.html.erb
<%= form_for :tema, :url => { :action => :create} do |f| %>
  <% if @tema.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tema.errors.count, "error") %> prohibited this question from being saved:</h2>
      <ul>
      <% @tema.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Escriba el nombre del tema" %><br>
    <%= f.text_field :nombretema %>
  </div>

  <div class="field">
    <%= f.label "Escriba la descripción del tema" %><br>
    <%= f.text_field :descripcion %>

  </div>
  <br>
  <div class="field">

    <%= f.label "Elija un temario" %>
      <br>
      <%= f.select(:temarioid,Temario.all.map{ |te| [ te.nombretemario, te.id ] }) %>
  </div>
    <br>
  <div class="actions">
    <%= f.submit "Guardar Tema" %>
  </div>
<% end %>

app/views/admin/temas/edit.html.erb
<h1>Editar tema</h1>
<%= form_for :tema, :url => { :action => :edit} do |f| %>
  <% if @tema.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tema.errors.count, "error") %> prohibited this question from being saved:</h2>
      <ul>
      <% @tema.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label "Escriba el nombre del tema" %><br>
    <%= f.text_field :nombretema %>
  </div>

  <div class="field">
    <%= f.label "Escriba la descripción del tema" %><br>
    <%= f.text_field :descripcion %>

  </div>
  <br>
  <div class="field">

    <%= f.label "Elija un temario" %>
      <br>
      <%= f.select(:temarioid,Temario.all.map{ |te| [ te.nombretemario, te.id ] }) %>
  </div>
    <br>
  <div class="actions">
    <%= f.submit "Guardar Tema" %>
  </div>
<% end %>

<%= link_to 'Atras', admin_temas_path %>

app/views/admin/temas/index.html.erb


<p id="notice"><%= notice %></p>

<h1>Temas</h1>
<%= breadcrumbs  :pretext => "Você está aqui: ", :separator => " &rsaquo;", :display_single_fragment => true%>

<table border="1">
  <col width="150">
  <col width="160">
  <col width="150">

  <thead>
    <tr>
      <th>Nombre del tema</th>
        <th>Descripción</th>


      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tema.each do |tema| %>
      <tr>
        <td><%= tema.nombretema %></td>
          <td><%= tema.descripcion %></td>


        <td><%= link_to 'Show', controller: "temas", action: "show", id: tema.id  %></td>
        <td><%= link_to 'Editar', edit_admin_tema_path(tema) %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @tema,  :previous_label => 'Atrás', :next_label => 'Adelante'%>
<br>

<%= link_to 'Nuevo tema', new_admin_tema_path %>

app/views/admin/temas/new.html.erb
<h1>nuevo tema</h1>
<%= render 'form' %>
<%= link_to 'Atras', admin_temas_path %>

app/views/admin/temas/show.html.erb
<h1>Tema</h1>
<%= breadcrumb :tema, @tema %>
<p>
  <strong>Nombre:</strong>
  <%= @tema.nombretema %>
</p>

<p>
  <strong>Descripción:</strong>
  <%= @tema.descripcion %>
</p>

<p>
  <strong>Quizzes:</strong>
</p>

<table border="1">
  <col width="150">
  <col width="160">
  <col width="150">
  <col width="50">
  <thead>
    <tr>
      <th>Nombre del quizz</th>
        <th>Disponibilidad</th>

      <th colspan="5"></th>
    </tr>
  </thead>
  <tbody>
    <% @quizzes.each do |q| %>
      <tr>
                <% if (@tema.id==q.temaid) %>
        <td><%= q.nombre %></td>
          <% if q.disponible? %>
<td> Disponible</td>
            <% else %>
<td> No Disponible</td>
              <% end %>
                            <td><%= link_to 'Show', controller: "quizzs", action: "show", id: q.id  %></td>
                          <td><%= link_to 'Edit', edit_admin_quizz_path(q) %></td>
    <% end %>

    <% end %>

  </tbody>
</table>
<%= will_paginate @quizzes,  :previous_label => 'Atrás', :next_label => 'Adelante'%>
<br>
<%= link_to 'Index', admin_temas_path %>
<%= link_to 'Atras',:back %>